# Generated by Django 4.0.3 on 2022-03-09 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidding',
            name='address',
        ),
        migrations.RemoveField(
            model_name='bidding',
            name='google_ad_acc_id',
        ),
        migrations.AlterField(
            model_name='bidding',
            name='bidding',
            field=models.CharField(choices=[('High', 'HIGH'), ('Medium', 'MEDIUM'), ('Low', 'LOW')], max_length=10),
        ),
    ]
