# Generated by Django 4.0.3 on 2022-03-09 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0002_remove_bidding_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='bidding',
            field=models.CharField(choices=[('H', 'HIGH'), ('M', 'MEDIUM'), ('L', 'LOW')], max_length=10),
        ),
    ]
