# Generated by Django 4.0.3 on 2022-03-09 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0003_alter_bidding_bidding'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='google_ads_account_id',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
    ]
